
export interface Job {
    jobId?: string;
    jobFunction: string;
    jobLocation: string;
    jobPost: string;
    experience: string;
    positions: number;
    fulfilledPositions: number;
    openPositions: number;
    receivedApplications: number;
    availableApplications: number;
    action?: string;
    status: string;
  }

  export const JOBS: Job[] = [
    {
      jobId: '1J001',
      jobFunction: 'IT',
      jobLocation: 'Nilai',
      jobPost: 'Analyst',
      experience: '12 - 15',
      positions: 5,
      fulfilledPositions: 2,
      openPositions: 5,
      receivedApplications: 20,
      availableApplications: 5,
      action: '',
      status: 'Open',
    },
    {
      jobId: '1J002',
      jobFunction: 'Marketing',
      jobLocation: 'Kuala Lumpur',
      jobPost: 'Marketing Specialist',
      experience: '8 - 10',
      positions: 3,
      fulfilledPositions: 1,
      openPositions: 2,
      receivedApplications: 15,
      availableApplications: 3,
      action: '',
      status: 'Closed',
    },
    {
      jobId: '1J003',
      jobFunction: 'Finance',
      jobLocation: 'Penang',
      jobPost: 'Financial Analyst',
      experience: '10 - 12',
      positions: 4,
      fulfilledPositions: 3,
      openPositions: 1,
      receivedApplications: 18,
      availableApplications: 2,
      action: '',
      status: 'Open',
    },
    {
      jobId: '1J004',
      jobFunction: 'Human Resources',
      jobLocation: 'Johor Bahru',
      jobPost: 'HR Manager',
      experience: '15+',
      positions: 2,
      fulfilledPositions: 1,
      openPositions: 1,
      receivedApplications: 25,
      availableApplications: 5,
      action: '',
      status: 'Open',
    },
    {
      jobId: '1J005',
      jobFunction: 'Engineering',
      jobLocation: 'Cyberjaya',
      jobPost: 'Systems Engineer',
      experience: '7 - 9',
      positions: 6,
      fulfilledPositions: 4,
      openPositions: 2,
      receivedApplications: 30,
      availableApplications: 8,
      action: '',
      status: 'Open',
    },
    {
      jobId: '1J006',
      jobFunction: 'Healthcare',
      jobLocation: 'Kota Kinabalu',
      jobPost: 'Medical Officer',
      experience: '5 - 7',
      positions: 8,
      fulfilledPositions: 6,
      openPositions: 2,
      receivedApplications: 22,
      availableApplications: 4,
      action: '',
      status: 'Open',
    },
    {
      jobId: '1J007',
      jobFunction: 'Education',
      jobLocation: 'Petaling Jaya',
      jobPost: 'Teacher',
      experience: '3 - 5',
      positions: 10,
      fulfilledPositions: 7,
      openPositions: 3,
      receivedApplications: 28,
      availableApplications: 6,
      action: '',
      status: 'Open',
    },
    {
      jobId: '1J008',
      jobFunction: 'Sales',
      jobLocation: 'Kuching',
      jobPost: 'Sales Representative',
      experience: '6 - 8',
      positions: 4,
      fulfilledPositions: 2,
      openPositions: 2,
      receivedApplications: 14,
      availableApplications: 3,
      action: '',
      status: 'Closed',
    },
    {
      jobId: '1J009',
      jobFunction: 'Research',
      jobLocation: 'Malacca',
      jobPost: 'Research Scientist',
      experience: '10 - 12',
      positions: 3,
      fulfilledPositions: 1,
      openPositions: 2,
      receivedApplications: 20,
      availableApplications: 4,
      action: '',
      status: 'Open',
    },
    {
      jobId: '1J010',
      jobFunction: 'Hospitality',
      jobLocation: 'Langkawi',
      jobPost: 'Hotel Manager',
      experience: '15+',
      positions: 2,
      fulfilledPositions: 1,
      openPositions: 1,
      receivedApplications: 15,
      availableApplications: 2,
      action: '',
      status: 'Open',
    },
  ];
  